spring.application.name=backend
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/todos}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:todos}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:todos}
spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
spring.jpa.open-in-view=false
